hyperskill_project:
  id: 313
  ide_files: https://stepik.org/media/attachments/lesson/856917/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Sun, 22 Jan 2023 02:44:52 UTC"
stages:
- id: 1756
  step: 24558
  is_completed: true
- id: 1757
  step: 24559
  is_completed: true
- id: 1758
  step: 24560
  is_completed: true
- id: 1759
  step: 24561
  is_completed: true
- id: 1760
  step: 24562
  is_completed: true
- id: 1761
  step: 24563
  is_completed: true
- id: 1762
  step: 24564
  is_completed: true
- id: 1763
  step: 24565
  is_completed: false
topics:
  0:
  - title: "Write, compile, and run"
    theory_id: 3739
  - title: "JVM, JRE, and JDK"
    theory_id: 3499
  - title: Interface elements
    theory_id: 15253
  - title: Input fields and field labels
    theory_id: 15447
  - title: Units of information
    theory_id: 6865
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Computer algorithms
    theory_id: 16547
  - title: Immutability
    theory_id: 7929
  - title: World Wide Web
    theory_id: 6633
  - title: HyperText Transfer Protocol
    theory_id: 6569
  - title: The big O notation
    theory_id: 16699
  - title: "Best, average and worst cases"
    theory_id: 20084
  - title: Data structures
    theory_id: 16927
  - title: HTTP URL
    theory_id: 6740
  - title: Block-level elements
    theory_id: 7271
  - title: Inline elements
    theory_id: 7518
  - title: What is CSS
    theory_id: 7678
  - title: Connecting CSS to HTML
    theory_id: 7418
  - title: Basic syntax
    theory_id: 7722
  - title: Comments
    theory_id: 7730
  - title: Relative units
    theory_id: 10671
  - title: Absolute units
    theory_id: 10605
  - title: HTML attributes id and class
    theory_id: 7527
  - title: CSS Selectors
    theory_id: 7738
  - title: Introduction to Flexbox
    theory_id: 11760
  - title: Orientation and Display order
    theory_id: 11768
  - title: "Flexibility, growth and contraction ratio"
    theory_id: 18859
  - title: Axis alignment
    theory_id: 11784
  - title: Introduction to Spring Web MVC
    theory_id: 13611
  - title: Intro to HTML forms
    theory_id: 6560
  - title: Form elements
    theory_id: 21167
  - title: Form attributes
    theory_id: 21174
  - title: Input types
    theory_id: 21151
  - title: Input attributes
    theory_id: 21158
  - title: More input attributes
    theory_id: 21187
  - title: Computer programming
    theory_id: 8739
  - title: Paradigms
    theory_id: 15860
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  - title: Types and variables
    theory_id: 3518
  - title: Comments
    theory_id: 3520
  - title: Scanning the input
    theory_id: 9055
  - title: Coding style conventions
    theory_id: 12411
  - title: Naming variables
    theory_id: 3513
  - title: Arithmetic operations
    theory_id: 3519
  - title: Integer types and operations
    theory_id: 3565
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Conditional statement
    theory_id: 3503
  - title: Ternary operator
    theory_id: 3506
  - title: Increment and decrement
    theory_id: 5008
  - title: The while and do-while loops
    theory_id: 3498
  - title: The for-loop
    theory_id: 3505
  - title: Branching statements
    theory_id: 3507
  - title: Switch statement
    theory_id: 3504
  - title: Sizes and ranges
    theory_id: 3532
  - title: Type casting
    theory_id: 3510
  - title: Calling a method
    theory_id: 10973
  - title: Declaring a method
    theory_id: 10982
  - title: The main method
    theory_id: 3489
  - title: Functional decomposition
    theory_id: 10570
  - title: Overloading
    theory_id: 3525
  - title: Primitive and reference types
    theory_id: 5035
  - title: Array
    theory_id: 3511
  - title: Arrays as parameters
    theory_id: 3594
  - title: Iterating over arrays
    theory_id: 3602
  - title: Characters
    theory_id: 3514
  - title: String
    theory_id: 3523
  - title: Final variables
    theory_id: 7427
  - title: Errors in programs
    theory_id: 3536
  - title: What is an exception
    theory_id: 3497
  - title: NPE
    theory_id: 1945
  - title: Introduction to OOP
    theory_id: 3614
  - title: Package
    theory_id: 3621
  - title: Build tools
    theory_id: 4284
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Java Archive
    theory_id: 4311
  - title: Gradle basics
    theory_id: 5075
  - title: Basic project with Gradle
    theory_id: 5077
  - title: Building apps using Gradle
    theory_id: 7917
  - title: Dependency management
    theory_id: 5076
  - title: Pseudocode
    theory_id: 15090
  - title: Pseudocode basics
    theory_id: 19510
  - title: Complex constructions in pseudocode
    theory_id: 20922
  - title: Fixed-size array
    theory_id: 20078
  - title: Dynamic array
    theory_id: 5357
  - title: Web development
    theory_id: 13931
  - title: External resources
    theory_id: 6216
  - title: HTML basics
    theory_id: 6434
  - title: Tags and Attributes
    theory_id: 7536
  - title: HTML page structure
    theory_id: 6491
  - title: Comments
    theory_id: 7502
  - title: Position
    theory_id: 11581
  - title: Float
    theory_id: 12697
  - title: Clear
    theory_id: 12705
  - title: Margin and Padding
    theory_id: 8346
  - title: Positioning properties
    theory_id: 8204
  - title: Width and Height
    theory_id: 8325
  - title: IntelliJ IDEA
    theory_id: 3801
  - title: Border
    theory_id: 8355
  - title: Text Alignment
    theory_id: 11589
  - title: Introduction to software architecture
    theory_id: 15368
  - title: Intro to Lists
    theory_id: 8178
  - title: "Headings, Paragraphs, Comments"
    theory_id: 21203
  - title: Introduction to generic programming
    theory_id: 3492
  - title: What are collections
    theory_id: 3770
  - title: ArrayList
    theory_id: 3567
  - title: MVC
    theory_id: 17197
  - title: Defining classes
    theory_id: 3618
  - title: Constructor
    theory_id: 3535
  - title: Instance methods
    theory_id: 3495
  - title: Access modifiers
    theory_id: 3589
  - title: Getters and setters
    theory_id: 3599
  - title: Inheritance
    theory_id: 3583
  - title: Multiple constructors
    theory_id: 3538
  - title: The keyword super
    theory_id: 3588
  - title: Objects
    theory_id: 4727
  - title: Static members
    theory_id: 3534
  - title: Boxing and unboxing
    theory_id: 3595
  1:
  - title: Comments
    theory_id: 8170
  - title: DOM
    theory_id: 8635
  - title: Connecting JavaScript to HTML
    theory_id: 7510
  - title: Introduction to JavaScript
    theory_id: 8016
  - title: Overview of the basic program
    theory_id: 8154
  - title: Multi-line programs
    theory_id: 8162
  - title: Variables
    theory_id: 8186
  - title: Strings and Numbers
    theory_id: 8194
  - title: Arithmetic operators
    theory_id: 8372
  - title: Functions
    theory_id: 8388
  - title: Defining functions
    theory_id: 24012
  - title: Builtin JS Functions
    theory_id: 24019
  - title: setTimeout and setInterval
    theory_id: 9680
  - title: Anonymous Function
    theory_id: 10865
  - title: Arrow Functions
    theory_id: 8455
  - title: Introduction to Arrays
    theory_id: 16141
  - title: Array creation
    theory_id: 16356
  - title: Boolean and Logical Operators
    theory_id: 8471
  - title: Increment and Decrement
    theory_id: 9102
  - title: Intro to DOM events
    theory_id: 10857
  - title: JSON
    theory_id: 6854
  - title: Introduction to Objects
    theory_id: 8588
  - title: Null and Undefined
    theory_id: 8564
  - title: Type Conversion
    theory_id: 8380
  - title: Comparison Operators
    theory_id: 8580
  - title: Conditional Operators
    theory_id: 8889
  - title: For Loops
    theory_id: 9119
  - title: While Loops
    theory_id: 9128
  - title: Switch
    theory_id: 10689
  - title: Break and Continue
    theory_id: 9374
  - title: DOM methods
    theory_id: 8662
  - title: The "addEventListener" method
    theory_id: 8723
  - title: Keyboard events handling
    theory_id: 8898
  - title: Modifying DOM
    theory_id: 21549
  - title: Advanced DOM methods
    theory_id: 21560
  - title: ClassList
    theory_id: 11653
  2:
  - title: Introduction to Spring Boot
    theory_id: 7944
  - title: Getting started with Spring Boot
    theory_id: 6336
  - title: Basic project structure
    theory_id: 6339
  - title: IoC Container
    theory_id: 16851
  - title: Spring beans
    theory_id: 14641
  - title: Spring components
    theory_id: 14652
  - title: The concept of patterns
    theory_id: 3611
  - title: HTTP messages
    theory_id: 6752
  - title: REST
    theory_id: 7834
  - title: Postman
    theory_id: 8512
  - title: Getting data from REST
    theory_id: 13287
  - title: Posting and deleting data via REST
    theory_id: 13292
  - title: Exception handling
    theory_id: 8780
  - title: Bean validation
    theory_id: 9355
  - title: Libraries
    theory_id: 8504
  - title: Frameworks
    theory_id: 6701
  - title: What is a bug
    theory_id: 5504
  - title: Functional testing
    theory_id: 13438
  - title: Unit testing
    theory_id: 7545
  - title: Dependency injection
    theory_id: 20580
  - title: Interfaces
    theory_id: 9640
  - title: YAML
    theory_id: 12722
  - title: Generics and Object
    theory_id: 3493
  - title: The Collections Framework overview
    theory_id: 3624
  - title: The List interface
    theory_id: 3581
  - title: The Set interface
    theory_id: 3575
  - title: The utility class Collections
    theory_id: 3573
  - title: Introduction to creational patterns
    theory_id: 16251
  - title: "Hashing: overview"
    theory_id: 9831
  - title: Hash function
    theory_id: 10878
  - title: Hash table
    theory_id: 13054
  - title: The Map interface
    theory_id: 3558
  - title: HashMap
    theory_id: 12379
  - title: Builder pattern
    theory_id: 16735
  - title: Builder
    theory_id: 5130
  - title: Protected modifier
    theory_id: 6692
  - title: Referencing subclass objects
    theory_id: 3585
  - title: The Object class
    theory_id: 3596
  - title: Annotations basics
    theory_id: 3622
  - title: Hiding and overriding
    theory_id: 3572
  - title: Polymorphism
    theory_id: 3587
  - title: Interface
    theory_id: 3615
  3:
  - title: Visibility
    theory_id: 10840
  - title: Handling requests with bodies
    theory_id: 13334
  - title: Intro to Tables
    theory_id: 10832
  - title: Date
    theory_id: 23067
  - title: Display
    theory_id: 21211
  - title: LocalDate
    theory_id: 3592
  - title: LocalTime
    theory_id: 3593
  - title: LocalDateTime
    theory_id: 3617
